name: htmlproofer

# Validates all links are up to date on the website

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages
  schedule:
      - cron: '0 0 * * SAT'

jobs:
  checklinks:
    name: Check links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: setup ruby
        uses: ruby/setup-ruby@v1
      - name: bundle install
        run: |
          gem update --system --no-document
          gem update bundler --no-document
          bundle install
      - name: build jekyll
        run: bundle exec jekyll build
      - name: htmlproofer
        run: |
          bundle add html-proofer
          bundle install
          bundle exec htmlproofer ./_site
